name: Clang Static Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clang-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang clang-tools cmake make python3

      - name: Set up Pico SDK
        run: |
          git clone --depth=1 https://github.com/raspberrypi/pico-sdk.git
          cd pico-sdk
          git submodule update --init
          echo "export PICO_SDK_PATH=$(pwd)" >> $GITHUB_ENV
          echo "export PICO_BOARD=pico_w" >> $GITHUB_ENV

      - name: Build and analyze
        env:
          PICO_SDK_PATH: ${{ env.PICO_SDK_PATH }}
          PICO_BOARD: pico_w
        run: |
          mkdir -p build
          cd build
          scan-build cmake ..
          scan-build make

      - name: Upload scan-build results
        uses: actions/upload-artifact@v2
        with:
          name: scan-build-results
          path: build/scan-build*
